language: go
go:
  - 1.14.3

git:
  depth: false

before_script:
  - export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
  - go get gopkg.in/yaml.v2

script:
  - go run main.go

deploy:
  provider: pages # 重要，指定这是一份 GitHub Pages 的部署配置
  skip-cleanup: true # 重要，不能省略
  local-dir: build # 静态站点文件所在目录
  target-branch: gh-pages # 要将静态站点文件发布到哪个分支
  github-token: $GITHUB_TOKEN # 重要，$GITHUB_TOKEN 是变量，需要在 GitHub 上申请、再到配置到 Travis https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token
  email: caizhenghai@gmail.com
  name: forecho
  fqdn: api.cashwarden.com # 如果是自定义域名，此处要填
  keep-history: true # 是否保持 target-branch 分支的提交记录
  on:
    branch: master # 博客源码的分支

notifications:
  slack: forecho:SQsHQyf5h6ibbGJAr501gff0
